### ISSUE TITLE
Update readme to prevent breaking html systax highlighting

### ISSUE THREAD

**Issue by IkBenOlie5** [ngalaiko/tree-sitter-go-template#21]
When using the instructions in the readme file, I got confused because when I created a .gotmpl the template code would get syntax highlighting but the highlighting of the html would break. I would suggest adding to the readme that in order for the gotmpl highlighting to work, one would need to add the file `.config/nvim/queries/gotmpl/injections.scm`:
```scm
(text) @yaml

((text) @injection.content
 (#set! injection.language "html")
 (#set! injection.combined))

((text) @injection.content
 (#set! injection.language "javascript")
 (#set! injection.combined))
```
to get the proper injections.

**Comment by qvalentin** [comment]
Good point, but from my understanding the snippet you posted does not really make sense.

`(text) @yaml` this has no effect i guess?

You also enabled both html and javascript injections at the same time, so the text nodes will be parsed with both parsers and the highlighting will be somewhat random (it is even flickering for me).
If your template files contain html and js it would be the best to use the js injections since this also supports jsx I guess.

Either way we can improve the readme and tell the user that he should add the injection for whatever language he is using inside the templates, sadly this can not be inferred from filetypes.

**Comment by IkBenOlie5** [comment]
Yeah I took the snippet from some random place (I have not the syntax myself) :).

**Comment by qvalentin** [comment]
I opened a PR here and also for [go.nvim](https://github.com/ray-x/go.nvim/pull/507)

Feel free to check it out.

**Comment by IkBenOlie5** [comment]
Great!
